from fpdf import FPDF
from datetime import datetime


def _clean_text(text: str) -> str:
    """
    Replaces or removes characters not supported
    by Helvetica font in fpdf2.
    """
    if not text:
        return ''

    replacements = {
        '\u2192': '->',   # →
        '\u2190': '<-',   # ←
        '\u2191': '^',    # ↑
        '\u2193': 'v',    # ↓
        '\u2022': '-',    # •
        '\u2013': '-',    # –
        '\u2014': '-',    # —
        '\u201c': '"',    # "
        '\u201d': '"',    # "
        '\u2018': "'",    # '
        '\u2019': "'",    # '
        '\u2026': '...',  # …
        '\u2705': '',     # ✅
        '\u274c': '',     # ❌
        '\u2713': 'OK',   # ✓
        '\u2b50': '*',    # ⭐
        '\u2665': '',     # ♥
        '\u25cf': '-',    # ●
    }

    for char, replacement in replacements.items():
        text = text.replace(char, replacement)

    # Remove any remaining non-latin characters
    result = ''
    for char in text:
        if ord(char) < 256:
            result += char
        else:
            result += ' '
    return result.strip()


class RetroPDF(FPDF):
    def __init__(self, sprint_name):
        super().__init__()
        self.sprint_name = _clean_text(sprint_name)
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        self.set_margins(20, 20, 20)

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(134, 188, 37)
        self.cell(0, 10, "RetroHub", ln=False, align="L")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(150, 150, 150)
        # No special characters in header
        self.cell(
            0, 10,
            "Reflect. Improve. Deliver.",
            ln=True,
            align="R"
        )

        self.set_draw_color(134, 188, 37)
        self.set_line_width(0.5)
        self.line(20, 22, 190, 22)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        # Use plain dash instead of em dash
        self.cell(
            0, 10,
            f"Generated by RetroHub on "
            f"{datetime.now().strftime('%d %b %Y')} - "
            f"Reflect. Improve. Deliver.",
            align="C"
        )

    def add_sprint_header(self, session: dict):
        # Sprint name
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 30, 30)
        self.cell(
            0, 10,
            _clean_text(session.get('sprint_name', '')),
            ln=True,
            align="L"
        )

        self.ln(2)

        # Sprint meta
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(
            0, 6,
            f"Sprint Dates: "
            f"{_clean_text(str(session.get('start_date', '')))} to "
            f"{_clean_text(str(session.get('end_date', '')))}",
            ln=True
        )
        self.cell(
            0, 6,
            f"Team Size: {session.get('team_size', '')} members",
            ln=True
        )

        self.ln(2)

        # Sprint goal
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(0, 6, "Sprint Goal", ln=True)

        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.set_fill_color(245, 245, 245)
        self.multi_cell(
            0, 6,
            _clean_text(session.get('sprint_goal', '')),
            fill=True
        )

        self.ln(4)

        self.set_draw_color(220, 220, 220)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(6)

    def add_section(self, title: str, content: str, color: tuple):
        # Section title with colored left bar
        self.set_fill_color(*color)
        self.rect(20, self.get_y(), 2, 8, "F")

        self.set_x(24)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, _clean_text(title), ln=True)
        self.ln(2)

        if content and content.strip():
            lines = content.split('\n')
            for line in lines:
                line = line.strip()
                if not line:
                    continue

                # Clean bullet and special characters
                line = _clean_text(line)
                if line.startswith('-'):
                    line = line[1:].strip()
                if not line:
                    continue

                self.set_font("Helvetica", "", 10)
                self.set_text_color(60, 60, 60)
                self.set_x(20)

                # Bullet dot
                self.set_fill_color(*color)
                self.ellipse(
                    20, self.get_y() + 3,
                    2, 2, "F"
                )
                self.set_x(25)
                self.multi_cell(0, 6, line)
                self.ln(1)
        else:
            self.set_font("Helvetica", "I", 10)
            self.set_text_color(150, 150, 150)
            self.set_x(20)
            self.cell(
                0, 6,
                "No content in this section.",
                ln=True
            )

        self.ln(4)


def generate_retro_pdf(session: dict, summary: dict) -> bytes:
    """
    Generates a PDF for the retro summary.
    Returns PDF as bytes for Streamlit download.
    """
    pdf = RetroPDF(session.get('sprint_name', 'Retro Summary'))

    pdf.add_sprint_header(session)

    sections = [
        (
            "What Went Well",
            summary.get('went_well_summary', ''),
            (134, 188, 37)
        ),
        (
            "What Can Be Improved",
            summary.get('improve_summary', ''),
            (0, 163, 224)
        ),
        (
            "Recognitions",
            summary.get('recognition_summary', ''),
            (245, 166, 35)
        ),
        (
            "Action Items",
            summary.get('action_items_summary', ''),
            (224, 82, 82)
        ),
    ]

    for title, content, color in sections:
        if pdf.get_y() > 240:
            pdf.add_page()
        pdf.add_section(title, content, color)

    return bytes(pdf.output())